### DISCUSSION TITLE
use MkDocs

### DISCUSSION THREAD

**Discussion by fu-sen** [domcloud/domcloud#3] [Ideas]
You can deploy MkDocs using templates:
```
source: .zip file URL or git repository
directory: extract directory
root: public_html/site
features:
- ssl
nginx:
  ssl: enforce
  error_pages:
  - 404 /404.html
commands:
- pip install --user -r requirements.txt
- mkdocs build
```

List the required pip packages (`mkdocs`, themes and plugins)  in `requirements.txt`, For example:
```
mkdocs
mkdocs-bootswatch
mkdocs-minify-plugin
```
