### DISCUSSION TITLE
Is there a way to add environment variables?

### DISCUSSION THREAD

**Discussion by lbrdt** [domcloud/domcloud#36] [General]
I checked the "Secret Variables" under the "Admin" dropdown in the dashboard but it is blank.

![image](https://user-images.githubusercontent.com/87078313/224522377-746c97d0-539c-4506-bf68-3d0dc7d43569.png)

**Comment by willnode** [comment]
Adding environment variables can be done through Nginx (via check -> Nginx), through [env_var_list](https://domcloud.co/docs/features/runner#passenger). For example, here's one from mine for a typical Node.js app:

```
root: public_html/public
nginx:
  passenger:
    enabled: 'on'
    app_start_command: env PORT=$PORT node app.js
    env_var_list:
      - NODE_ICU_DATA=.
```

Another way to do it is via `~/.bashrc` as per [passenger docs here](https://www.phusionpassenger.com/docs/advanced_guides/in_depth/ruby/environment_variables.html)

```bash
export FOO=bar
```

(After changing this file don't forget to [restart your app](https://domcloud.co/docs/deployment/node#restart-nodejs))

Secret variables are different, it is meant to be used only using runner (for CI purposes). For now, it is just used for giving Git tokens when pulling repos via Runner or Webhook.
