### DISCUSSION TITLE
How to deploy stremio-gdrive?

### DISCUSSION THREAD

**Discussion by aicynide** [domcloud/domcloud#37] [Q&A] [answered]
Complete step by step guide please

https://github.com/ssnjr2002/stremio-gdrive/ <-- repo

**Comment by willnode** [comment, marked as answer]
Roughly the template will look like this:

```yaml
features:
- python 3.9.9
root: public_html/public
source: https://github.com/ssnjr2002/stremio-gdrive/
commands:
- mkdir public
- pip install -r requirements.txt --user
nginx:
  passenger:
    enabled: on
    app_start_command: gunicorn sgd:app -b :$PORT --timeout 60
```

Be warned that video proxy or web streaming service is [prohibited under ToS](https://domcloud.co/service).
