### DISCUSSION TITLE
Host telegram bot?

### DISCUSSION THREAD

**Discussion by gbox1** [domcloud/domcloud#38] [Q&A]
hello admin i came here to ask you that ,how to host telegram bot here?

**Comment by willnode** [comment]
I assume you came here with basic experience on how to [create a telegram bot](https://docs.python-telegram-bot.org/en/stable/) that works when you run locally.

In DOM Cloud, it's slightly different. You can't run a telegram bot by polling. You have to run it using [webhooks](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Webhooks).

With webhook, you have to run your app based on PORT env that is specified by envs like this:

```
import os

TOKEN = "TOKEN"
PORT = int(os.environ.get('PORT', '8443'))
# add handlers
application.run_webhook(
    listen="0.0.0.0",
    port=PORT,
    secret_token='ASecretTokenIHaveChangedByNow',
    webhook_url="https://<appname>.domcloud.io/"
)
```

Then setup nginx (via Check -> Nginx tab) like this:

```yaml
root: public_html/public
nginx:
  passenger:
    enabled: on
    app_start_command: env PORT=$PORT python app.py
```
