### DISCUSSION TITLE
use Hugo

### DISCUSSION THREAD

**Discussion by fu-sen** [domcloud/domcloud#5] [Ideas]
You can build Hugo using templates, :
```
source: .zip file URL or git repository
directory: extract directory
root: public_html/public
features:
- ssl
nginx:
  ssl: enforce
  error_pages:
  - 404 /404.html
commands:
- git submodule update --init --recursive
- curl -sS https://webinstall.dev/webi | bash
- webi hugo@0.83.1
- hugo
```
It adopts `Hugo 0.83.1`. You can change the Hugo version.
You can also give options to `hugo`. For example: `hugo --minify`

The file structure of Hugo changes depending on the application of the theme. Therefore, I dare not prepare a sample.
