### DISCUSSION TITLE
Could not install puppeteer (PHP & NodeJS deployment)

### DISCUSSION THREAD

**Discussion by JNussenzveig** [domcloud/domcloud#72] [Q&A] [answered]
Hi, I've deployed my Laravel app and it works great, but I also need puppeteer as a dependency (I use spatie/browsershot).

When I tried to install, the following error occurs:
![image](https://github.com/domcloud/domcloud/assets/7662734/6f543c9a-ad43-413a-bd7c-a1dbf7a85ecf)

Is there a browser already installed? Should I do anything different?

Can anyone help, please? Thanks in advance!

**Comment by willnode** [comment]
The download is blocked because of [the firewall](https://domcloud.co/docs/integration/troubleshoot#connection-refused-when-connecting-to-third-party-api).

The download URL can be [inferred from here](https://github.com/puppeteer/puppeteer/tree/823f8688f22a0685dc8f05bb400995c371935c37/packages/browsers/src/browser-data). But I think I'm hesitant to add it on the whitelist right now.

The best way to do this is to do `npm i` via [The Deployment System](https://domcloud.co/docs/features/deploy#firewall). Because things executed there don't get blocked via Firewall temporarily even for free users:

```
commands:
- npm i
```

**Comment by JNussenzveig** [comment]
Thanks for the response! Using `npm i`:

![image](https://github.com/domcloud/domcloud/assets/7662734/00cfa372-ec3a-43a5-bd87-d0615d0ad765)

It's a screenshot from the actual build/deployment task.

I'm also using

```
features:
   - node latest
```

What should I try?

**Comment by JNussenzveig** [comment]
Deployment file:

```
features:
  -
    create:
      ...
  - firewall
  - 'php latest'
  - mysql
  - ssl
  - 'ssl always'
  - 'node latest'
nginx:
  root: public_html/public
  fastcgi: 'on'
  locations:
    -
      match: /
      try_files: '$uri $uri/ /index.php$is_args$args'
    -
      match: '~ \.[^\/]+(?<!\.php)$'
      try_files: '$uri =404'
commands:
  - 'cp .env.example .env'
  - 'sed -i "s/DB_HOST=127.0.0.1/DB_HOST=localhost/g" .env'
  - 'sed -ri "s/DB_DATABASE=.*/DB_DATABASE=${DATABASE}/g" .env'
  - 'sed -ri "s/DB_USERNAME=.*/DB_USERNAME=${USERNAME}/g" .env'
  - 'sed -ri "s/DB_PASSWORD=.*/DB_PASSWORD=${PASSWORD}/g" .env'
  - 'sed -ri "s/APP_URL=.*/APP_URL=http:\/\/${DOMAIN}/g" .env'
  - 'composer install'
  - 'php artisan migrate:fresh || true'
  - 'php artisan key:generate'
  - 'php artisan storage:link'
  - 'npm i'
  - 'npm run build'
  - 'rm -f public/hot'
  - 'chmod g+r -R storage || true'
```
