### ISSUE TITLE
Running a NodeJS server throws a "listen EACCES" error.

### ISSUE THREAD

**Issue by xefyrdev** [domcloud/domcloud#50]
I am trying to start [my NodeJS application](https://github.com/xefyrdev/discord-bio-links), however when I do so, I get the following error:

<img width="477" alt="error message" src="https://github.com/domcloud/domcloud/assets/139470244/9a9181f8-908d-479b-88fb-ad86a585dd10">

This is the line of code that tries to start the server:

```ts
// cfg.port is 443 here.
appServer.listen(cfg.port, () => console.log(`Server launched and listening at port ${cfg.port}`));
```

**Comment by willnode** [comment]
You can't run Node.js app and directly bind to 80 or 443, because it has to be routed via NginX. If you looked at [an example template in Node.js](https://github.com/domcloud/recipes/blob/master/node.yml) it uses this config in NGINX to hook `server.listen`:

```yaml
nginx:
  root: public_html/public
  passenger:
    enabled: "on"
    app_type: node
    startup_file: app.js
    node: .local/opt/node/bin/node
```

If your app is a module-based Node.js app or need to some port, use [the ESM config](https://github.com/domcloud/recipes/blob/master/node-esm.yml) and make sure the app listen to `$PORT`:

```
nginx:
  root: public_html/public
  passenger:
    enabled: "on"
    app_start_command: env PORT=$PORT node app.js
```

```
server.listen(process.env.PORT || 8080);
```

Read more [in the docs](https://domcloud.co/docs/features/nginx#configure-nginx-for-general-apps).
